//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public int UserId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
