//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string UrlStandart { get; set; }
        public string UrlMedium { get; set; }
        public string UrlSmall { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> PostId { get; set; }
        public int AlbumId { get; set; }
        public int UserId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
