//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public album()
        {
            this.comments = new HashSet<comment>();
            this.pictures = new HashSet<picture>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> likes { get; set; }
        public bool @private { get; set; }
        public int userId { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<picture> pictures { get; set; }
    }
}
