//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string comment1 { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<int> albumId { get; set; }
        public Nullable<int> pictureId { get; set; }
        public int userId { get; set; }
    
        public virtual album album { get; set; }
        public virtual picture picture { get; set; }
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
