//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.userRoles = new HashSet<userRole>();
        }
    
        public string roleName { get; set; }
    
        public virtual ICollection<userRole> userRoles { get; set; }
    }
}
