//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.albums = new HashSet<album>();
            this.comments = new HashSet<comment>();
            this.pictures = new HashSet<picture>();
            this.posts = new HashSet<post>();
            this.userRoles = new HashSet<userRole>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surName { get; set; }
        public string alias { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string avaUrl { get; set; }
        public bool isRemoved { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<album> albums { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<picture> pictures { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<userRole> userRoles { get; set; }
    }
}
